### ISSUE TITLE
Suggestion: Re-roll button

### ISSUE THREAD

**Issue by valchiara** [QinomeD/Naming-Unconvention#1]
Just a small quality of life feature, I think it would be nice to have a button that re-rolls the generated name. Currently you have to exit and re-enter the world creation screen, which can take some time, especially when loading a bunch of datapacks.

**Comment by QinomeD** [comment]
just go with the first name it gives you lulz

I'll look into that

**Comment by QinomeD** [comment]
ok I figured out that adding a button might collide with some other mods altering the world creation screen, so instead you will be able to reroll with a keybind (default: N)

**Comment by QinomeD** [comment]
ok setting a letter to a re-roll keybind is a super duper bad idea lmao
